from pathlib import Path

from fastapi import FastAPI
from fastapi.testclient import TestClient

from kiwi_scan.api.ui import mount_static, router as ui_router


def _make_ui_client() -> TestClient:
    app = FastAPI()
    mount_static(app)
    app.include_router(ui_router)
    return TestClient(app)


def test_pro_dashboard_serves_fault_summary_and_receiver_health_hooks() -> None:
    client = _make_ui_client()

    response = client.get("/pro")

    assert response.status_code == 200
    assert response.headers["cache-control"] == "no-store, no-cache, must-revalidate, max-age=0"

    html = response.text
    required_snippets = [
        '<h2 data-icon="sliders">Receiver Statistics</h2>',
        'id="chip-rx-health"',
        'id="assignments-band-cards"',
        'id="overview-board"',
        'data-overview-key="status"',
        'data-overview-key="receiver-scan"',
        'id="cfg-overview-receiver-scan"',
        'id="settings-automation-title">Receiver Mode<',
        'id="auto-fixed-plan-card"',
        'id="auto-fixed-plan-rows"',
        'id="auto-mode-enabled"',
        'id="auto-status"',
        'data-nav="receiver-scan"',
        'id="receiver-scan"',
        'aria-label="Collapse Receiver Scan"',
        'id="receiver-scan-smart-start"',
        'id="receiver-scan-smart-band"',
        'id="receiver-scan-cw-start"',
        'id="receiver-scan-phone-start"',
        'id="receiver-scan-smart-results-card"',
        'id="receiver-scan-cw-results-card"',
        'id="receiver-scan-phone-results-card"',
        'id="receiver-scan-smart-heading"',
        'id="receiver-scan-smart-status"',
        'id="receiver-scan-smart-cw-results"',
        'id="receiver-scan-smart-phone-results"',
        'id="net-monitor"',
        'aria-label="Collapse 20m NET Monitor"',
        'id="net-monitor-start"',
        'id="net-monitor-capture"',
        'id="receiver-scan-mode-state"',
        'id="net-monitor-mode-state"',
        'id="net-monitor-capture-state"',
        'id="net-monitor-transcript-state"',
        'id="receiver-scan-cw-current"',
        'id="receiver-scan-phone-current"',
        'id="net-monitor-history"',
        'id="net-monitor-capture-summary"',
        'id="net-monitor-transcript-summary"',
        'id="net-monitor-transcript-text"',
        'id="receiver-scan-cw-results"',
        'id="receiver-scan-phone-results"',
        'class="receiver-scan-metrics"',
        'const RECEIVER_SCAN_BANDS = ["20m", "40m"]',
        'const NET_MONITOR_CAPTURE_DURATION_S = 20',
        'function readSelectedReceiverScanBand()',
        'function normalizeReceiverScanBand(value, fallback = "40m")',
        'function syncReceiverScanControls(scan = latestReceiverScanStatus)',
        'function initReceiverScanResultCardToggles()',
        'function applyReceiverScanResultCardCollapsedState(card, collapsed, persist = false)',
        'function syncReceiverScanResultCards(scan = latestReceiverScanStatus)',
        'function applyReceiverScanSmartCard(scan, lanes, results)',
        'function focusReceiverScanLane(role)',
        'function syncNetMonitorControls(status = latestNetMonitorStatus)',
        'function renderNetMonitorCapture(status = latestNetMonitorStatus)',
        'function renderNetMonitorTranscript(status = latestNetMonitorStatus)',
        'function levelToClass(level)',
        'function titleLevel(level)',
        'function renderReceivers(channels)',
        'function applyReceiverScanStatus(scan)',
        'function applyNetMonitorStatus(status)',
        'function stopReceiverScanRun(options = {})',
        'panelId === "net-monitor" && navId === "receiver-scan"',
        'getJson("/net_monitor/status", TIMEOUT)',
        'getJson("/receiver_scan/status", TIMEOUT)',
        'getJson("/decodes/ws_status", DECODE_WS_CLIENT_POLL_TIMEOUT_MS)',
        '&& Number(item && item.event_count) > 0;',
        'if (kind === "cw") return Number(item && item.signal_count) > 0;',
        'No confirmed phone-like IQ clusters detected.',
        'No persistent CW-like tones detected.',
        'await postJson("/net_monitor/start", {})',
        'await postJson("/net_monitor/capture", { duration_s: NET_MONITOR_CAPTURE_DURATION_S })',
        'await postJson("/net_monitor/deactivate", {})',
        'await postJson("/receiver_scan/start", { band: targetBand })',
        'await postJson("/receiver_scan/start", {})',
        'await postJson("/receiver_scan/deactivate", {})',
        'Smart Scan for ${selectedBandValue || "that band"} is not available yet',
        'Transcript text will appear here after capture completes.',
        'renderNetMonitorTranscript(status);',
        'Receiver Scan started on ${startedBand}. Restart the backend to load ${targetBand} band selection.',
        'await runReceiverScanControl("cw");',
        'await runReceiverScanControl("phone");',
        'runStartupStep("initReceiverScanResultCardToggles", () => initReceiverScanResultCardToggles());',
        '<option value="160m">160m</option>',
        'const runningSameBand = !!(scan && scan.running && activeBand === selectedBandValue);',
        'localStorage.setItem(UI_DENSITY_STORAGE_KEY, density);',
        'const storedThemeMode = readStoredUiThemeMode();',
        'byId("chip-rx-health").innerHTML = `Active: ${active}<br>Warn: ${silent + warn}<br>Faulty: ${unstable}`;',
        '<h2 data-icon="alert">Fault Summary</h2>',
        'id="summary-fault-load"',
        'id="reasons"',
        'function renderReasons(reasonCounts)',
        'el.innerHTML = "<li>No active faults</li>";',
        'faultEl.textContent = `fault:${unstable} warn:${warns} reasons:${totalFaultReasons}`;',
        'renderReasons(h.reason_counts || {});',
        'class="status-chip status-chip-stream" data-icon="stream">',
        'id="chip-stream">Connecting...</div>',
        'class="status-chip status-chip-rx-summary" data-icon="shield">',
        'class="status-chip-head">',
        'class="chip-label chip-label-secondary" data-icon="signal">Busiest Band</div>',
        'class="chip-side-value" id="chip-busiest-band">...</div>',
        'class="chip-side-label" data-icon="signal">All Decodes</div>',
        'class="chip-side-value" id="chip-all-decodes">...</div>',
        'class="status-chip status-chip-empty" aria-hidden="true"></article>',
        'function displayManagedReceiverPrefix(value)',
        'return prefix.startsWith("ROAM") ? "ROAM" : prefix;',
        'const readableMatch = raw.match(/^(AUTO|FIXED|ROAM(?:\\d+)?)_([^_]+)_(.+)$/i);',
        '|| /^(AUTO|FIXED|ROAM(?:\\d+)?)_([^_]+)_(.+)$/i.test(raw);',
        'if (digitalModes.length >= 3) return "ALL";',
        'if (digitalModes.length >= 2) return "MIX";',
        'function fmtCount(value) {',
        'function scheduleRecentDecodePanelRender()',
        'ingestDecodeItem(item, { renderList: false, renderMap: false });',
        'const healthCounts = {};',
        'const busiestCounts = healthDecodeTotal > 0 ? healthCounts : counts;',
        'byId("chip-all-decodes").textContent = fmtCount(totalDecodes);',
    ]

    for snippet in required_snippets:
        assert snippet in html

    forbidden_snippets = [
        '<a href="#trend" data-nav="trend" data-icon="trend">Decode Trend</a>',
        '<article class="panel" id="trend">',
        'id="cfg-overview-trend"',
        'id="cfg-overview-summary"',
        'id="cfg-overview-balance"',
        'id="assignment-balance-panel"',
        'data-nav="automation"',
        '<article class="panel" id="automation">',
        'id="auto-alerts-enabled"',
        'id="auto-alert-threshold"',
        'id="auto-quiet-start"',
        'id="auto-quiet-end"',
        'class="autosave-badge">Autosave On</span>',
        'id="auto-reload"',
        'id="auto-apply-now"',
        'id="auto-ui-theme-mode"',
        'id="auto-ui-density"',
        'previewUiPreferencesFromAutomation',
        'byId("auto-ui-theme-mode")',
        'byId("auto-ui-density")',
        'auto-scan-on-block',
        'auto-refresh-schedule',
        'auto-scan-on-startup',
        'auto-ssb-enabled',
        'function updateAutomationSsbStepVisibility(strategyValue)',
        'const autoSsbStepStrategy = byId("auto-ssb-step-strategy");',
        'bcCurrentMode',
        'bc-mode-toggle',
        'bc-mode-btn',
        '/smart_scheduler/status?mode=',
        'byId("auto-apply-mode")',
        'mode === "phone" ? "SSB" : "FT8"',
        'id="auto-apply-mode"',
        'id="auto-selected-bands"',
        'data-nav="summary"',
        'id="summary-busiest-band"',
        'id="chip-stream-4010-count"',
        'id="chip-stream-4020-count"',
        'UDP: 4010</div>',
        '<article class="status-chip" data-icon="signal">',
    ]

    for snippet in forbidden_snippets:
        assert snippet not in html


def test_prod_minimal_pro_template_keeps_fault_summary_and_receiver_health_hooks() -> None:
    workspace_root = Path(__file__).resolve().parents[1]
    prod_template = workspace_root / "prod_minimal" / "src" / "kiwi_scan" / "static" / "pro.html"

    html = prod_template.read_text(encoding="utf-8")
    required_snippets = [
        '<h2 data-icon="sliders">Receiver Statistics</h2>',
        'id="chip-rx-health"',
        'id="assignments-band-cards"',
        'id="overview-board"',
        'data-overview-key="status"',
        'data-overview-key="receiver-scan"',
        'id="cfg-overview-receiver-scan"',
        'id="settings-automation-title">Receiver Mode<',
        'id="auto-fixed-plan-card"',
        'id="auto-fixed-plan-rows"',
        'id="auto-mode-enabled"',
        'id="auto-status"',
        'data-nav="receiver-scan"',
        'id="receiver-scan"',
        'aria-label="Collapse Receiver Scan"',
        'id="receiver-scan-smart-start"',
        'id="receiver-scan-smart-band"',
        'id="receiver-scan-cw-start"',
        'id="receiver-scan-phone-start"',
        'id="receiver-scan-smart-results-card"',
        'id="receiver-scan-cw-results-card"',
        'id="receiver-scan-phone-results-card"',
        'id="receiver-scan-smart-heading"',
        'id="receiver-scan-smart-status"',
        'id="receiver-scan-smart-cw-results"',
        'id="receiver-scan-smart-phone-results"',
        'id="net-monitor"',
        'aria-label="Collapse 20m NET Monitor"',
        'id="net-monitor-start"',
        'id="net-monitor-capture"',
        'id="receiver-scan-mode-state"',
        'id="net-monitor-mode-state"',
        'id="net-monitor-capture-state"',
        'id="net-monitor-transcript-state"',
        'id="receiver-scan-cw-current"',
        'id="receiver-scan-phone-current"',
        'id="net-monitor-history"',
        'id="net-monitor-capture-summary"',
        'id="net-monitor-transcript-summary"',
        'id="net-monitor-transcript-text"',
        'id="receiver-scan-cw-results"',
        'id="receiver-scan-phone-results"',
        'class="receiver-scan-metrics"',
        'const RECEIVER_SCAN_BANDS = ["20m", "40m"]',
        'const NET_MONITOR_CAPTURE_DURATION_S = 20',
        'function readSelectedReceiverScanBand()',
        'function normalizeReceiverScanBand(value, fallback = "40m")',
        'function syncReceiverScanControls(scan = latestReceiverScanStatus)',
        'function initReceiverScanResultCardToggles()',
        'function applyReceiverScanResultCardCollapsedState(card, collapsed, persist = false)',
        'function syncReceiverScanResultCards(scan = latestReceiverScanStatus)',
        'function applyReceiverScanSmartCard(scan, lanes, results)',
        'function focusReceiverScanLane(role)',
        'function syncNetMonitorControls(status = latestNetMonitorStatus)',
        'function renderNetMonitorCapture(status = latestNetMonitorStatus)',
        'function renderNetMonitorTranscript(status = latestNetMonitorStatus)',
        'function renderReceivers(channels)',
        'function applyReceiverScanStatus(scan)',
        'function applyNetMonitorStatus(status)',
        'function stopReceiverScanRun(options = {})',
        'panelId === "net-monitor" && navId === "receiver-scan"',
        'getJson("/net_monitor/status", TIMEOUT)',
        'getJson("/receiver_scan/status", TIMEOUT)',
        'getJson("/decodes/ws_status", DECODE_WS_CLIENT_POLL_TIMEOUT_MS)',
        '&& Number(item && item.event_count) > 0;',
        'if (kind === "cw") return Number(item && item.signal_count) > 0;',
        'No confirmed phone-like IQ clusters detected.',
        'No persistent CW-like tones detected.',
        'await postJson("/net_monitor/start", {})',
        'await postJson("/net_monitor/capture", { duration_s: NET_MONITOR_CAPTURE_DURATION_S })',
        'await postJson("/net_monitor/deactivate", {})',
        'await postJson("/receiver_scan/start", { band: targetBand })',
        'await postJson("/receiver_scan/start", {})',
        'await postJson("/receiver_scan/deactivate", {})',
        'Smart Scan for ${selectedBandValue || "that band"} is not available yet',
        'Transcript text will appear here after capture completes.',
        'renderNetMonitorTranscript(status);',
        'Receiver Scan started on ${startedBand}. Restart the backend to load ${targetBand} band selection.',
        'await runReceiverScanControl("cw");',
        'await runReceiverScanControl("phone");',
        'runStartupStep("initReceiverScanResultCardToggles", () => initReceiverScanResultCardToggles());',
        '<option value="160m">160m</option>',
        'const runningSameBand = !!(scan && scan.running && activeBand === selectedBandValue);',
        'localStorage.setItem(UI_DENSITY_STORAGE_KEY, density);',
        'const storedThemeMode = readStoredUiThemeMode();',
        '<h2 data-icon="alert">Fault Summary</h2>',
        'id="summary-fault-load"',
        'id="reasons"',
        'function renderReasons(reasonCounts)',
        'el.innerHTML = "<li>No active faults</li>";',
        'renderReasons(h.reason_counts || {});',
        'class="status-chip status-chip-stream" data-icon="stream">',
        'id="chip-stream">Connecting...</div>',
        'class="status-chip status-chip-rx-summary" data-icon="shield">',
        'class="status-chip-head">',
        'class="chip-label chip-label-secondary" data-icon="signal">Busiest Band</div>',
        'class="chip-side-value" id="chip-busiest-band">...</div>',
        'class="chip-side-label" data-icon="signal">All Decodes</div>',
        'class="chip-side-value" id="chip-all-decodes">...</div>',
        'class="status-chip status-chip-empty" aria-hidden="true"></article>',
        'function displayManagedReceiverPrefix(value)',
        'return prefix.startsWith("ROAM") ? "ROAM" : prefix;',
        'const readableMatch = raw.match(/^(AUTO|FIXED|ROAM(?:\\d+)?)_([^_]+)_(.+)$/i);',
        '|| /^(AUTO|FIXED|ROAM(?:\\d+)?)_([^_]+)_(.+)$/i.test(raw);',
        'if (digitalModes.length >= 3) return "ALL";',
        'if (digitalModes.length >= 2) return "MIX";',
        'function fmtCount(value) {',
        'function scheduleRecentDecodePanelRender()',
        'ingestDecodeItem(item, { renderList: false, renderMap: false });',
        'const healthCounts = {};',
        'const busiestCounts = healthDecodeTotal > 0 ? healthCounts : counts;',
        'byId("chip-all-decodes").textContent = fmtCount(totalDecodes);',
    ]

    for snippet in required_snippets:
        assert snippet in html

    forbidden_snippets = [
        '<a href="#trend" data-nav="trend" data-icon="trend">Decode Trend</a>',
        '<article class="panel" id="trend">',
        'id="cfg-overview-trend"',
        'id="cfg-overview-summary"',
        'id="cfg-overview-balance"',
        'id="assignment-balance-panel"',
        'data-nav="automation"',
        '<article class="panel" id="automation">',
        'id="auto-alerts-enabled"',
        'id="auto-alert-threshold"',
        'id="auto-quiet-start"',
        'id="auto-quiet-end"',
        'class="autosave-badge">Autosave On</span>',
        'id="auto-reload"',
        'id="auto-apply-now"',
        'id="auto-ui-theme-mode"',
        'id="auto-ui-density"',
        'previewUiPreferencesFromAutomation',
        'byId("auto-ui-theme-mode")',
        'byId("auto-ui-density")',
        'auto-scan-on-block',
        'auto-refresh-schedule',
        'auto-scan-on-startup',
        'auto-ssb-enabled',
        'function updateAutomationSsbStepVisibility(strategyValue)',
        'const autoSsbStepStrategy = byId("auto-ssb-step-strategy");',
        'bcCurrentMode',
        'bc-mode-toggle',
        'bc-mode-btn',
        '/smart_scheduler/status?mode=',
        'byId("auto-apply-mode")',
        'mode === "phone" ? "SSB" : "FT8"',
        'id="auto-apply-mode"',
        'id="auto-selected-bands"',
        'data-nav="summary"',
        'id="summary-busiest-band"',
        'id="chip-stream-4010-count"',
        'id="chip-stream-4020-count"',
        'UDP: 4010</div>',
        '<article class="status-chip" data-icon="signal">',
        'id="receiver-scan-start-20m"',
        'id="receiver-scan-start"',
        'id="receiver-scan-stop"',
    ]

    for snippet in forbidden_snippets:
        assert snippet not in html